name: mlflow-project-env
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch

dependencies:
  - python=3.9
  - pip=24.2
  - setuptools=75.1.0
  - wheel=0.37.1
  - pip:
      - mlflow
      - cloudpickle==3.1.1
      - torch==2.5.0
      - torchvision==0.20.0
      - torchaudio==2.1.0
